# Generated by Django 4.2.13 on 2024-05-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('stars', models.TextField()),
                ('country', models.TextField()),
                ('city', models.TextField()),
                ('rooms', models.TextField()),
                ('number_of_rooms', models.TextField()),
            ],
        ),
    ]
