# Generated by Django 4.2.13 on 2024-05-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
