# Generated by Django 4.2.13 on 2024-05-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_remove_hotel_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('room_number', models.TextField()),
                ('number_of_guests', models.TextField()),
                ('price', models.TextField()),
                ('size', models.TextField()),
            ],
        ),
    ]
