# Generated by Django 4.2.13 on 2024-05-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='rooms',
        ),
    ]
