# Generated by Django 4.2.13 on 2024-05-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0007_remove_hotel_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rooms',
            field=models.ManyToManyField(related_name='rooms', to='booking_app.room'),
        ),
    ]
