# Generated by Django 4.2.13 on 2024-05-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0008_hotel_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='city',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='country',
        ),
    ]
