# Generated by Django 4.2.13 on 2024-05-25 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0009_rename_city_hotel_location_remove_hotel_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='rooms',
        ),
    ]
