# Generated by Django 4.2.13 on 2024-05-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0011_room_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
    ]
