# Generated by Django 4.2.13 on 2024-05-25 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0012_remove_room_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rooms',
            field=models.ManyToManyField(related_name='hotels', to='booking_app.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms_as_foreign_key', to='booking_app.hotel'),
        ),
    ]
