# Generated by Django 4.2.13 on 2024-05-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0014_alter_room_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
    ]
