# Generated by Django 4.2.13 on 2024-05-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0017_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
