# Generated by Django 4.2.13 on 2024-05-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0024_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
